### ISSUE TITLE
How do I set a fixed footer in this html_to_doc?

### ISSUE THREAD

**Issue by hemsbansal** [Korchy/html_to_doc#1]
Hey @Korchy , can you help me to set a fixed footer in this html_to_doc ?

**Comment by Korchy** [comment]
Hi!
You mean .doc colontitles? I'm afraid that this could not be done. HTML doesn't have colontitles, usually such thinks make with CSS styles. Unfortunatelly I don't know how to send some styles to .doc colontitles.

**Comment by hemsbansal** [comment]
yeah, I've just tried via css and it worked fine with some minor issues, hopefully that'll also get fixed.  thanks!
